CREATE OR REPLACE TRIGGER Admin_Id_Trg
BEFORE INSERT ON Admin
FOR EACH ROW
BEGIN
    IF :NEW.Admin_Id IS NULL THEN
        SELECT Admin_Id_seq.NEXTVAL INTO :NEW.Admin_Id FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER Customer_Id_Trg
BEFORE INSERT ON Customer
FOR EACH ROW
BEGIN
    IF :NEW.Customer_Id IS NULL THEN
        SELECT Customer_Id_seq.NEXTVAL INTO :NEW.Customer_Id FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER Order_Id_Trg
BEFORE INSERT ON Orders
FOR EACH ROW
BEGIN
    IF :NEW.Order_Id IS NULL THEN
        SELECT Order_Id_seq.NEXTVAL INTO :NEW.Order_Id FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER Product_Id_Trg
BEFORE INSERT ON Product
FOR EACH ROW
BEGIN
    IF :NEW.Product_Id IS NULL THEN
        SELECT Product_Id_seq.NEXTVAL INTO :NEW.Product_Id FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER Review_Id_Trg
BEFORE INSERT ON Review
FOR EACH ROW
BEGIN
    IF :NEW.Review_Id IS NULL THEN
        SELECT Review_Id_seq.NEXTVAL INTO :NEW.Review_Id FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER Shop_Id_Trg
BEFORE INSERT ON Shop
FOR EACH ROW
BEGIN
    IF :NEW.Shop_Id IS NULL THEN
        SELECT Shop_Id_seq.NEXTVAL INTO :NEW.Shop_Id FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER Time_Slot_Id_Trg
BEFORE INSERT ON Time_Slot
FOR EACH ROW
BEGIN
    IF :NEW.Time_Slot_Id IS NULL THEN
        SELECT Time_Slot_Id_seq.NEXTVAL INTO :NEW.Time_Slot_Id FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER Trader_Id_Trg
BEFORE INSERT ON Trader
FOR EACH ROW
BEGIN
    IF :NEW.Trader_Id IS NULL THEN
        SELECT Trader_Id_seq.NEXTVAL INTO :NEW.Trader_Id FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER Cart_Id_Trg
BEFORE INSERT ON Cart
FOR EACH ROW
BEGIN
    IF :NEW.Cart_Id IS NULL THEN
        SELECT Cart_Id_seq.NEXTVAL INTO :NEW.Cart_Id FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER Trader_Status_Trg
BEFORE INSERT ON Trader
FOR EACH ROW
BEGIN
    IF :NEW.Status IS NULL THEN
        :NEW.Status := 'pending';
    END IF;
END;
/
